name = "Shattered Reality"
author = "Azure Fey MC"
version = "5.2.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c44f9c363693d1d3270ae64d09ce0612c42a474c5f9964d3943aa4d777b2d591"

[versions]
fabric = "0.18.4"
minecraft = "1.20.1"
