name = "Shattered Reality"
author = "Azure Fey MC"
version = "5.1.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7fe5ef56880926348ea9dcd2dbd0eb55ec37fa724fa529ffe2e4ab5ca1e8f5a8"

[versions]
fabric = "0.18.4"
minecraft = "1.20.1"
