name = "Shattered Reality"
author = "Azure Fey MC"
version = "5.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "14c8a6f0cd151d2a991dcf0d4178862ee14782b03ee24b1e68f75acc2f2ac3d8"

[versions]
fabric = "0.18.4"
minecraft = "1.20.1"
