name: Update Pack
on:
  schedule:
    - cron:  '55 */6 * * *'
  workflow_dispatch:
jobs:
  pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: Open Checkout
        uses: actions/checkout@v1
      - name: Creates Pull Request
        uses: emiliopedrollo/create-pull-request@v2.0.0
        with:
          head: 1.20.1-dev
          base: 1.20.1-quilt
      - name: Merge PR
        uses: maxkomarychev/merge-pal-action@master
      
