name: Update Pack
on:
  schedule:
    - cron:  '55 */6 * * *'
  workflow_dispatch:
jobs:
  pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: Open Checkout
        uses: actions/checkout@v1
      - name: Create pull request
        uses: thomaseizinger/create-pull-request@master
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          head: 1.20.1-dev
          base: 1.20.1-quilt
          title: "Pack Update"
      - name: Merge PR
        uses: maxkomarychev/merge-pal-action@master
      
